import { t } from '../i18n';

/** Data-driven menu model → rendered by MenuBar. */
export interface MenuDef {
  id: string;
  title: () => string;
  items: (string | '-')[]; // command ids or separators
}

export const menus: MenuDef[] = [
  {
    id: 'file',
    title: () => t().menuFile,
    items: [
      'file.open',
      'file.url',
      'file.sample',
      '-',
      'file.recordSettings',
      'file.export',
      '-',
      'file.draftSave',
      'file.draftOpen',
    ],
  },
  {
    id: 'edit',
    title: () => t().menuEdit,
    items: [
      'edit.undo',
      'edit.redo',
      '-',
      'edit.cut',
      'edit.copy',
      'edit.paste',
      'edit.delete',
      '-',
      'clip.split',
      'clip.duplicate',
      'clip.delete',
      '-',
      'edit.trim',
      'edit.silence',
      '-',
      'edit.selectAll',
      'edit.deselect',
    ],
  },
  {
    id: 'effects',
    title: () => t().menuEffects,
    items: [
      'fx.rack',
      '-',
      'fx.compressor',
      'fx.limiter',
      '-',
      'fx.pgeq8',
      'fx.pgeq',
      'fx.geq10',
      'fx.geq20',
      '-',
      'fx.delay',
      'fx.reverb',
      'fx.reverb2',
      '-',
      'fx.chorus',
      'fx.flanger',
      'fx.phaser',
      'fx.tremolo',
      'fx.vibrato',
      'fx.distortion',
      '-',
      'fx.gate',
      'fx.deesser',
      'fx.nr3',
      'fx.nrPrint',
      'fx.rnvoice',
      'fx.rate',
      'fx.stretch',
      '-',
      'fx.gain',
      'fx.fadeIn',
      'fx.fadeOut',
      '-',
      'fx.normalize',
      'fx.normalizeLufs',
      'fx.reverse',
      'fx.invert',
      '-',
      'fx.removeSilence',
    ],
  },
  {
    id: 'analyze',
    title: () => t().menuAnalyze,
    items: [
      'analyze.lufs',
      'analyze.report',
      'analyze.bpm',
      '-',
      'analyze.beats',
      'analyze.panel',
    ],
  },
  {
    id: 'view',
    title: () => t().menuView,
    items: ['view.zoomIn', 'view.zoomOut', 'view.zoomReset', '-', 'view.center', '-', 'view.follow', 'view.zerocross', 'view.axis', 'view.theme', 'view.accent'],
  },
  {
    id: 'help',
    title: () => t().menuHelp,
    items: ['help.welcome', 'help.shortcuts', 'help.about', 'help.doctor'],
  },
];
